### ISSUE TITLE
Background color mismatch between website and Figma design

### ISSUE THREAD

**Issue by mariach44** [usamach559/Chatbot-Ai-front-end#1]
Description:
The background color of the website does not match the design specified in Figma. While the Figma design specifies a darker background, the frontend implementation displays a significantly lighter, almost white, background. 

![b1f94455-4433-442e-bcbb-ad6d6fe9d24d](https://github.com/user-attachments/assets/1f0efefc-e628-4e80-883f-c6d14b998127)

figma design

![4158e929-c953-4aea-9890-f601e5c58954](https://github.com/user-attachments/assets/529d1d93-43d8-4324-8c4c-1601789a06f5)

**Comment by Chaudharytouseef** [comment]
this is an image not a color

**Comment by mariach44** [comment]
sure
