### ISSUE TITLE
UI issue on AI writer page

### ISSUE THREAD

**Issue by mariach44** [usamach559/Chatbot-Ai-front-end#11]
![b0fc8cdb-3059-40b0-accb-de1b6f52efc3](https://github.com/user-attachments/assets/5234250d-661f-4083-b62c-84ed53b5c8a3)

Suggestion:
 This bug should be fixed when you attached link as per page so thats why its priority is low

**Comment by Chaudharytouseef** [comment]
Okay 👍

**Comment by Chaudharytouseef** [comment]
Backend developer will remove all code of the sidebars from the pages and use only one

**Comment by mariach44** [comment]
sure
