### ISSUE TITLE
UI issue of Affiliate page

### ISSUE THREAD

**Issue by mariach44** [usamach559/Chatbot-Ai-front-end#14]
1. **Button name should be change to new video as match with figma design**

### front end 
![3b3c8535-ece3-4748-b4e8-bb869d4970dc](https://github.com/user-attachments/assets/c38dc9cb-d81a-4e62-bec8-b2b84a080c14)
### figma design
![5b9f70e3-a7da-47cd-b631-92fab1cafbe5](https://github.com/user-attachments/assets/6ca6ea5d-3df2-434a-bf34-0780fe91a0b7)

1. **Email icon should be display under the email field just like figma design**

### **front end**
![61d0eece-1a52-4876-a46b-46a8a050fba4](https://github.com/user-attachments/assets/809011cb-f307-4ee4-b5b5-c445ad649f76)
### figma design
![8eb020f8-4b9b-4599-9726-5866058e99f4](https://github.com/user-attachments/assets/f03b5a74-524f-4307-87e6-ae36d35ecb0e)

### Web screen is cut at the edge of mobile scren
![e4f74540-80b7-481f-9e7d-4b333d7ca02e](https://github.com/user-attachments/assets/807ff063-855e-4ba0-b7b5-519f66fe5463)
###  
Shape of container is destory on mobile screen
![b250d47e-4275-45e7-9782-3a6963d5753b](https://github.com/user-attachments/assets/fe0795de-bee7-4492-8d55-3c45f9c6ed50)

Grid shape is destory on small screen
![7ff88a69-1a6e-4c46-bf23-1d59dcad0f4a](https://github.com/user-attachments/assets/3e29200b-2e9c-4d76-8f49-7a2a19d15758)

add margin on both side
![4e6fdd03-7da3-4685-97ea-1e80015cbe58](https://github.com/user-attachments/assets/aca82c52-d25f-4210-81b7-76a01b5c5829)

**Comment by mariach44** [comment]
Responsiveness Issue are still not resolved

@Chaudharytouseef

**Comment by Chaudharytouseef** [comment]
it is solved

**Comment by mariach44** [comment]
Responsiveness Issues
![6826286e-392d-4a53-a49c-a91def7dc6d2](https://github.com/user-attachments/assets/0b0694dc-3295-4886-a1ef-95112d72d022)
![48b0866e-ebfe-4441-8d56-fcd528112204](https://github.com/user-attachments/assets/2aeb36e4-db5b-422e-9d53-60573fad848c)
![50b09299-ceba-4a38-91eb-2edb2346effd](https://github.com/user-attachments/assets/a999c5ba-585e-4e64-b833-066334a442af)

@Chaudharytouseef

**Comment by mariach44** [comment]
Responsiveness Issue:

![036220f3-69c5-414e-b41e-2c79b106cea5](https://github.com/user-attachments/assets/a51b3037-ac8b-46ef-8dbb-0e5748a48ddd)
![5891bf52-20f6-453d-9c9d-109106fe643f](https://github.com/user-attachments/assets/7ef35fe2-b7cc-429c-88c1-248af49d887a)

@Chaudharytouseef

**Comment by mariach44** [comment]
This Issue has been resolved
