### ISSUE TITLE
Front end design and responsiveness issue of AI Social Media and Brand Center screens

### ISSUE THREAD

**Issue by mariach44** [usamach559/Chatbot-Ai-front-end#20]
### 1-page name tittle is wrong it should be "AI SOCIAL Media" 
on front end
![25f7010e-195f-4529-98db-1126fddb72a7](https://github.com/user-attachments/assets/48be3065-f2b2-4c1a-b4b3-b7962bfd7557)
### on figma design
![a055a904-69a2-432e-ad84-a21abcf1719d](https://github.com/user-attachments/assets/a66984d4-87d6-41d2-862d-b17821301a15)

### on front end
![9d75ccc7-e7f4-49d7-a7a2-c3981829f11b](https://github.com/user-attachments/assets/31b51290-d7d2-44f8-918b-bc28652e797f)

###3- button shape should be rounded as show in figma design
### on frontend
![fa34bc6d-2547-4966-aefb-ede0641ff775](https://github.com/user-attachments/assets/51fa2214-6f73-436b-af4a-2ee02183645e)
### on figma design
![2fc8846c-214d-42bf-8554-bcf1fabbe59d](https://github.com/user-attachments/assets/33045595-d44a-4dcb-bf8e-1195a94f4ed7)

### on frontend
![c59856fc-252a-4702-acc5-b98e5d057a91](https://github.com/user-attachments/assets/12c9c32d-8b1f-4827-8a3a-8f779856e68f)
### on figma design
![4d76ac46-5367-42eb-81f7-3c2c9c0b164e](https://github.com/user-attachments/assets/682dc7d9-1266-44d4-8f81-f94d44d305a2)

###5- use blur layout on the background of container
### on frontend
![56352e97-d772-4b98-b4f8-d49d9068e196](https://github.com/user-attachments/assets/3ed18398-086e-45e8-ab9c-a9d4e68cf279)
### on figma design
![d50fba9e-a05e-4840-9943-7d83372d47c4](https://github.com/user-attachments/assets/6ea4f75d-7acd-45cc-9a43-7aaba2e00f8b)

###6-hint text should be use in these fields
### on front end
![87e5d371-9599-4025-861e-dfd275335de7](https://github.com/user-attachments/assets/04a12556-456f-4ce8-b477-a5ce5bffc178)
### on figma design
![c5f21bde-d481-40a8-941f-3493a4d978a3](https://github.com/user-attachments/assets/b0cd408e-0e99-4442-b2ed-964db4a19a30)

### on frontend
![4bf74f43-f8ee-45ad-8f84-2a6e2f24ee5f](https://github.com/user-attachments/assets/e184c031-789a-492e-8331-22d0ba1f0869)
### on figma design
![a3dc5480-0148-4316-9e2e-2948fc7026f9](https://github.com/user-attachments/assets/9fef8ccf-127b-49ec-8476-3b4e4bba4a78)

Responsiveness Issues

![f7ac4231-2b5a-4d0e-81b9-7dccef373d16](https://github.com/user-attachments/assets/4bd4640f-651c-41dc-a77c-e60bbd7ec929)

![f9316202-d5c4-40a2-87f9-737e850ea8c7](https://github.com/user-attachments/assets/eb221f32-ad8d-44e4-aa47-c1e51479b9a1)
![a154c89c-14cd-4f5c-9ea5-10d8178acefa](https://github.com/user-attachments/assets/9cc8f996-c29d-4a69-a5d2-60e4c9928123)

**Comment by mariach44** [comment]
1- Search ICOn is overlap to text
![7cbb3b64-c123-461f-943a-7f99edb0e1e5](https://github.com/user-attachments/assets/b74de789-8096-49d2-91b6-95ab3341aa6b)

2-Button name is "New video" on figma design
on frontend
![4e5cafe7-2bd5-4d4b-8ea8-3f81885cafc6](https://github.com/user-attachments/assets/5eb23b50-c995-4ecb-a4d4-e278a8a6f9dd)
on figma
![2e1965c1-550e-466f-89cd-5e61814c1d6d](https://github.com/user-attachments/assets/a770cb3f-45b3-4b22-ae81-146d10fc1f61)

### Responsiveness Issues
1-
![7fe341f5-2712-4143-828f-e9276e9070de](https://github.com/user-attachments/assets/ba0da321-4cf1-44df-8396-9d87258150dc)
2-
![208059aa-1827-4c65-99c6-a377ae5257f2](https://github.com/user-attachments/assets/ad23df24-c552-4c3b-9f1f-d0c5cb1f5aaa)
3-
![e0f20744-d7e5-4d8c-8445-fcaad2bfe271](https://github.com/user-attachments/assets/3c9924e6-2d46-458f-8d6a-a1a5c11e8b10)
4-
![969c3d4d-9d77-47c5-b579-e5f88d3a1352](https://github.com/user-attachments/assets/b48fe470-59b8-4d72-b976-7d4efd5913e2)

@Chaudharytouseef

**Comment by mariach44** [comment]
1-ALL Responsiveness are still not resolved that mentioned in above
2- 
![0ae4ac5b-98f0-42ae-85a0-52723cfaed44](https://github.com/user-attachments/assets/47e9777a-c638-4f29-ad27-24301ee5ef97)
@Chaudharytouseef

**Comment by Chaudharytouseef** [comment]
> 1-ALL Responsiveness are still not resolved that mentioned in above 2- ![0ae4ac5b-98f0-42ae-85a0-52723cfaed44](https://private-user-images.githubusercontent.com/113729011/384593096-47e9777a-c638-4f29-ad27-24301ee5ef97.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzExNDUxMDQsIm5iZiI6MTczMTE0NDgwNCwicGF0aCI6Ii8xMTM3MjkwMTEvMzg0NTkzMDk2LTQ3ZTk3NzdhLWM2MzgtNGYyOS1hZDI3LTI0MzAxZWU1ZWY5Ny5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEwOVQwOTMzMjRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kYzc0MDkwMDE1MjQ5YTBhNDkwMzJiMzUwYzAwZmQ3Yzc5YmVhMDczMDdkYjk4ZGMyMmEyOTQ1ODI5N2I4MzBiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.VoVeIJaNBx-mdH-Ftg4HBlel_48l1ETPPgYTAI76hGE) @Chaudharytouseef

 twitter has to changed to x that's why we use x instead of twitter

**Comment by mariach44** [comment]
Ok got it but what about responsiveness issue 

1-
![4ed899c4-9e2f-4ced-a5f7-b03573db317b](https://github.com/user-attachments/assets/2d047751-edf2-4b9b-9455-399b971e8f57)
2-
![a0f9c163-1300-4675-ab85-6c803a04640b](https://github.com/user-attachments/assets/23990e2a-3d7a-43d7-8792-f71915574031)
3-
![b5131f30-f003-4b2c-9bb7-f8d1a21c52f1](https://github.com/user-attachments/assets/cdb0d580-1f45-4fc5-b43f-8d10d82488dc)

@Chaudharytouseef

**Comment by mariach44** [comment]
This issue has been resolved
