### ISSUE TITLE
Frontend design and responsiveness issue of AI voice isolator

### ISSUE THREAD

**Issue by mariach44** [usamach559/Chatbot-Ai-front-end#34]
1-Add two buttons on here "My documents" and "Add New" as show in figma design
On frontend
![329c74d6-d11b-43e2-8cbb-f31e356e69e2](https://github.com/user-attachments/assets/47379ea6-bf98-4591-a5f0-16d95963a1ff)
On Figma
![61129b49-a06e-4032-8dfa-4549970d85b6](https://github.com/user-attachments/assets/b914b850-38b4-4f6c-9a9b-28e842162075)

2-Use poppin regular
On frontend
![981cdb8b-470e-4a06-9480-ee06753bc893](https://github.com/user-attachments/assets/a670b7f2-da8e-4a77-8c4c-7b52c7a5516a)
![394781c9-2426-41f7-8aff-b4d329592587](https://github.com/user-attachments/assets/7b59d6e3-cf0f-4a51-b810-0af2798bf476)

3-Responsiveness Issue
 audio container are too small on mobile screen make it size adjustable as per screen 
![5a2a00ab-2169-4add-a744-a1e1c0f6addf](https://github.com/user-attachments/assets/65fa8398-66e7-46c9-aef7-81a0f7103b48)

**Comment by mariach44** [comment]
Point numberv 1 and 3 are still not resolve

@Chaudharytouseef

**Comment by Chaudharytouseef** [comment]
I can't find anything to solve the third one

**Comment by mariach44** [comment]
Tittle name is replace with AI voice Isolator
on front end
![4f728203-6776-49e5-8f99-ee56eb00800c](https://github.com/user-attachments/assets/11da97a5-3dff-42fe-b4c3-c89fdf9f61ff)
on figma
![e059656e-9a42-49b7-a98b-47f70741e671](https://github.com/user-attachments/assets/2d5363fa-14cc-4e4d-a33c-bfd837b3600c)

@Chaudharytouseef

**Comment by mariach44** [comment]
![1b665f06-fa11-4072-8f6d-aa6bb20ad7d5](https://github.com/user-attachments/assets/516ff75c-9f1f-4237-a5a3-00e8aacd78f1)

@Chaudharytouseef

**Comment by mariach44** [comment]
still not resolved 

@Chaudharytouseef

**Comment by mariach44** [comment]
![d299e132-f757-40ba-a166-d3cc7a579bda](https://github.com/user-attachments/assets/12b789b6-64bd-4428-93aa-c2b739a1a820)

@Chaudharytouseef

**Comment by mariach44** [comment]
This has been resolved
