### ISSUE TITLE
Frontend design issue and responsiveness issues of Vision AI screen

### ISSUE THREAD

**Issue by mariach44** [usamach559/Chatbot-Ai-front-end#41]
1-Add space before the right side of line
![ef286d88-dd42-4bdc-abe5-587f17cc4b75](https://github.com/user-attachments/assets/d3e407b8-f9a4-479f-a63d-79955722d59a)
on figma side
![71bb1923-30d9-40ea-b9b1-b3c9d70c1621](https://github.com/user-attachments/assets/98fcaff7-de8d-448f-88e8-8800b9e6535c)

2- Adjust icon alignment and remove space btw two layers
![9289a60c-2a97-4b26-a495-6875a95e07f7](https://github.com/user-attachments/assets/7eff4f92-52d3-430c-bb3c-f0e80e8b06d4)
![86392f6d-bed3-4b19-bded-21c44845edca](https://github.com/user-attachments/assets/c0c4c2cf-96e8-468b-bf8c-b52cf9f0b35c)
![f89cba72-a1ca-4d0e-a6db-e9467154f4fb](https://github.com/user-attachments/assets/8f0eca17-83c8-4332-be8a-664d6163275f)
on figma
![de7abd75-7936-4d39-a120-3b6a74cea828](https://github.com/user-attachments/assets/559cde19-4903-4451-8586-b8e44b89ffec)

### Responsiveness Issues

![828d744d-fc24-447f-8265-02a13fb7ad74](https://github.com/user-attachments/assets/5dfb5c19-3490-4714-93f8-3f97d72394bc)

Add little margin on upper layer of mobile screen
![a290e98f-777b-434c-88fd-f5eb0a0987d2](https://github.com/user-attachments/assets/35f30339-8139-4538-b47b-4129c4032952)

**Comment by mariach44** [comment]
@Chaudharytouseef 
you did not push the changing code of this screen
its not resolved on my side

**Comment by Chaudharytouseef** [comment]
check now

**Comment by mariach44** [comment]
Responsiveness issue

1-remove space btw these two grid
![8a4804ac-9e87-4920-89e6-eb1adf892ac4](https://github.com/user-attachments/assets/5a361b25-0ca4-42c6-bc2d-8caa3d998700)
2-Add margin on both side
![b6a85dfa-b1ad-4634-84c2-df5069bdddb5](https://github.com/user-attachments/assets/ee9ecc31-a08f-4c9e-af4e-b4b650b67906)
3-On mobile screen voice icon display out of the text field box
![ddc7cd32-0bfe-432c-b8ff-093d2381fbb2](https://github.com/user-attachments/assets/9fb6e5ce-cd8c-449b-ba3a-c7bda45edd16)

4-
![d324a5a0-7779-4bd7-8e8f-6ffd7fcb2053](https://github.com/user-attachments/assets/456cfaf2-dd76-48f7-a058-7f698d511d11)

@Chaudharytouseef

**Comment by mariach44** [comment]
Responsiveness Issues:

1- Adjust margin their margin
On frontend
![3e67f1d8-a9ab-4e50-889d-ae1bc2e44215](https://github.com/user-attachments/assets/beabc1c8-a576-4e56-8b7f-e2d7b4821c9d)
ON figma
![3efda07b-b049-4a90-86e7-75a90c3b0f65](https://github.com/user-attachments/assets/9a39c78e-f0a1-4613-95b4-a937ce55b98e)

2- Adjust margin on desktop screen
![b1b8de88-055d-42e1-bdea-c10b40adb423](https://github.com/user-attachments/assets/6cfaf889-bfa5-4fb7-9739-02ad7b0433a6)
3- Add space btw buttons and tittle on mobile screen
![610992a5-abe5-4999-9710-b328dad1399c](https://github.com/user-attachments/assets/1c05ad19-6642-4c95-a16b-f722f760967a)

4- Add margin on both side
![53bacc56-a6aa-41f9-b0cc-d287e34c0aad](https://github.com/user-attachments/assets/9511cfcc-d0db-4207-85be-0f944eca1665)

5-Adjust side msg line on single line on small desktop screen
![2da0b48b-1285-4829-9d08-d13326d715f9](https://github.com/user-attachments/assets/4ca3ddfe-e27a-4bc4-ab3c-f8ec5e9b55ed)

@Chaudharytouseef

**Comment by mariach44** [comment]
Responsiveness Issue:
1-
![b34e20e6-9b98-443c-a4d7-15b816ba72d2](https://github.com/user-attachments/assets/c6b06b34-06f1-483a-8015-f6b961218749)

2-
![586ce0d1-6b36-4d5d-b45c-6339eef21f4c](https://github.com/user-attachments/assets/d8a44d1f-eaac-4467-b68e-925b467ddcc8)
3-
![695722d3-e885-49f0-8a4f-df1e51162259](https://github.com/user-attachments/assets/a72bb30a-b6a2-4ef6-9131-31dab6168174)
4-
![8b735819-e4f2-4e92-b9da-aff42979ed3a](https://github.com/user-attachments/assets/eddb8949-bad7-4b8e-8570-00a9be6d0331)
5-
![d9501d27-30b0-4bbe-a45d-d58d815e3583](https://github.com/user-attachments/assets/4932bb4f-a96e-4f63-ac02-f1159812241f)
6-
![f68bd69b-c44a-4f9e-8a6f-993baaf785be](https://github.com/user-attachments/assets/0535deb8-1734-4d76-9d23-f570604d6b30)

@Chaudharytouseef

**Comment by Chaudharytouseef** [comment]
please guide about fifth  point

**Comment by mariach44** [comment]
5-
![ddc4ea8d-fea5-4316-9d8c-4dc78109163e](https://github.com/user-attachments/assets/3573ee16-960a-45fc-83a9-4725f90e2899)

@Chaudharytouseef

**Comment by mariach44** [comment]
![ebafdeaa-1b6e-4687-a100-7f704790c0b6](https://github.com/user-attachments/assets/b73bbaa3-6873-474f-9175-2d8d05e043d9)

when I rotate the web screen the grid is round at the end it should be straight like a square

@Chaudharytouseef

**Comment by mariach44** [comment]
This issue has been resolved
