### ISSUE TITLE
Frontend design Issue of Affilliates screen

### ISSUE THREAD

**Issue by mariach44** [usamach559/Chatbot-Ai-front-end#46]
Add equal space btw tittles
on frontend
![de5f0c27-350c-41fb-8fb9-4b6519d70f9a](https://github.com/user-attachments/assets/1f51196c-b8b9-4138-9f41-ca5e02853995)
on figma
![06fe3647-a539-4ef8-9e50-ccd4d0db0047](https://github.com/user-attachments/assets/4ab3a7a5-2328-497f-a124-5e59f22eb83a)

**Comment by mariach44** [comment]
![1b997c86-d899-4474-a7fc-1f209658ba70](https://github.com/user-attachments/assets/11d4d903-b986-4a88-93d4-c29ef15d3cf3)

@Chaudharytouseef

**Comment by Chaudharytouseef** [comment]
on which resolution @mariach44

**Comment by mariach44** [comment]
On sumsung ALL models @Chaudharytouseef also on iphone Xsmax
