### ISSUE TITLE
responsiveness issue of mobile and laptop screen of Dashboard screen

### ISSUE THREAD

**Issue by mariach44** [usamach559/Chatbot-Ai-front-end#6]
![d59c6f39-8e92-496c-8b79-2f045066ae2e](https://github.com/user-attachments/assets/a59825b1-b9db-4d76-a0e2-e5e9f654e010)

Button is overlap to eachother on small screen
![34fe9484-bb9b-45a9-8408-0c5330fb2fc8](https://github.com/user-attachments/assets/e3fac655-9efb-49ff-8cbf-c70234cac6c2)

![83383672-3c3c-4a78-b26c-684cafbf35a4](https://github.com/user-attachments/assets/e3956f0b-7cc9-4860-a0de-aebb35bc1e0b)

Burger menu is overlap the logo in small screen
![f693f951-59ec-4f9e-8fef-c0895ce23dab](https://github.com/user-attachments/assets/d3810a9f-08ec-4e25-aa2d-12bd3f7499f9)

**Comment by mariach44** [comment]
Burger menu is not working on small screens
![de504d28-d608-47c3-90ff-de31c464bc5a](https://github.com/user-attachments/assets/f5c7955f-8b27-4024-b4ce-6b0d17543fa5)

@Chaudharytouseef

**Comment by Chaudharytouseef** [comment]
Check now

**Comment by Chaudharytouseef** [comment]
Check now

**Comment by mariach44** [comment]
still not working @Chaudharytouseef

**Comment by Chaudharytouseef** [comment]
it is working 

Uploading Sidebar with Responsive Toggler - Google Chrome 2024-11-06 16-56-36.mp4…

**Comment by Chaudharytouseef** [comment]
it is working

**Comment by mariach44** [comment]
This issue has been resolved
