### ISSUE TITLE
frontend design and responsiveness issue of AI voiceover

### ISSUE THREAD

**Issue by mariach44** [usamach559/Chatbot-Ai-front-end#68]
1-All drop down menu options show out of the screen on mobile screen
![image](https://github.com/user-attachments/assets/5c7d8543-d2be-4d8f-9a59-c7ebf1a74748)

2- Design are missmatch with figma design
on frontend
![c3bfba73-da3e-4e0e-95a6-80b04c1c793d](https://github.com/user-attachments/assets/c775c44c-c256-4f02-852e-2411bf078a7a)
on figma
![ed489a9e-2ea5-46c7-af73-8089b6e0d0e1](https://github.com/user-attachments/assets/ac8c2618-f01a-4729-9447-50e1bf7b229e)

3-Design is missing on frontend
![4d86eb99-0ed2-4ead-a087-bb2312cee2f1](https://github.com/user-attachments/assets/d2310297-7cdf-473b-835a-0e76e176417b)

**Responsiveness Issue**

1-
![22d8086f-9788-4c5b-814b-9023e633e6ed](https://github.com/user-attachments/assets/41b4bd65-f8d2-416a-9e50-bab5de140cb7)
2-
![44e64b62-2aef-4251-bddb-4b7bdbf60498](https://github.com/user-attachments/assets/facae1a1-8310-467e-ba95-6e5f28b26020)

**Comment by Chaudharytouseef** [comment]
first one is invalid

**Comment by mariach44** [comment]
This issue has been resolved
