### ISSUE TITLE
Side Menu Title Text Color Remains White After active layout Moves to Another Title module

### ISSUE THREAD

**Issue by mariach44** [usamach559/Chatbot-Ai-front-end#7]
**Description:**
In the dashboard's side menu, when a active layout is on module tittle, the module title text color is expected to change to white, contrasting against the active layout color. However, occasionally, the title text color remains white even after the active layout has moved to a different module

**Expected Result:**
When a module is highlighted, its title text color should change to white. Once the active layout moves to a different module, the title text color of the previously active module should revert to its default color.

**Message typing:**
 Jb side menu ma purple active layout hta to text k color change ho jata hai white but jb active layout dosre tittle py aye to peechy wale text k color still white he rhta hai jb k asa nhi hona chahiya

front side image
![92966f3f-70db-436f-9af9-f2893f9491ad](https://github.com/user-attachments/assets/309ce430-3a6a-4e92-8496-2e628c7e468c)

**Comment by Chaudharytouseef** [comment]
Dashboad page  per sidebar thk ho gia ha

**Comment by mariach44** [comment]
this issue has been resolved
